services:
  - type: web
    name: woodstreambot
    env: docker
    repo: https://github.com/SudoR2spr/WOODStreamBot
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: ULOG_CHANNEL
        value: -100xxxxxxxxxx
      - key: FLOG_CHANNEL
        value: -100xxxxxxxxxx
      - key: DATABASE_URL
        value: your_mongodb_url
      - key: FQDN
        value: your_domain.com
      - key: HAS_SSL
        value: false
      - key: OWNER_ID
        value: your_owner_id
      - key: PORT
        value: 8080
